{
  "openapi": "3.0.0",
  "info": {
    "title": "classhire",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:{be_port}/api",
      "variables": {
        "be_port": {
          "default": "DefaultParameterValue"
        }
      }
    }
  ],
  "paths": {
    "/auth/login": {
      "post": {
        "tags": [
          "Account / Auth"
        ],
        "summary": "Login - /api/auth/login",
        "operationId": "Login-/api/auth/login",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/Login-apiauthloginRequest"
                  },
                  {
                    "example": {
                      "email": "gaxelac@outlook.com",
                      "password": "123456"
                    }
                  }
                ]
              },
              "example": {
                "email": "gaxelac@outlook.com",
                "password": "123456"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/auth/signup": {
      "post": {
        "tags": [
          "Account / Auth"
        ],
        "summary": "Sign Up - /api/auth/signup",
        "operationId": "SignUp-/api/auth/signup",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/SignUp-apiauthsignupRequest"
                  },
                  {
                    "example": {
                      "email": "gaxelac@outlook.com",
                      "name": "Gaston Axel Lacuesta",
                      "password": "123456",
                      "photo": ""
                    }
                  }
                ]
              },
              "example": {
                "email": "gaxelac@outlook.com",
                "name": "Gaston Axel Lacuesta",
                "password": "123456",
                "photo": ""
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/clase": {
      "get": {
        "tags": [
          "Clases"
        ],
        "summary": "Get Clase - /api/clase",
        "operationId": "GetClase-/api/clase",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "enum": [
                "application/json"
              ],
              "type": "string",
              "example": "application/json"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/clase/add": {
      "post": {
        "tags": [
          "Clases"
        ],
        "summary": "Add Clase - /api/clase/add",
        "operationId": "AddClase-/api/clase/add",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/AddClase-apiclaseaddRequest"
                  },
                  {
                    "example": {
                      "price": 5,
                      "title": "gaxelac3@outlook.com",
                      "description": "blabla",
                      "frecuencia": [
                        {
                          "value": "diaria"
                        }
                      ]
                    }
                  }
                ]
              },
              "example": {
                "price": 5,
                "title": "gaxelac3@outlook.com",
                "description": "blabla",
                "frecuencia": [
                  {
                    "value": "diaria"
                  }
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/profile": {
      "get": {
        "tags": [
          "Profiles"
        ],
        "summary": "Get Profile - /api/profile",
        "operationId": "GetProfile-/api/profile",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "enum": [
                "application/json"
              ],
              "type": "string",
              "example": "application/json"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "Login-apiauthloginRequest": {
        "title": "Login-apiauthloginRequest",
        "required": [
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "email": "gaxelac@outlook.com",
          "password": "123456"
        }
      },
      "SignUp-apiauthsignupRequest": {
        "title": "SignUp-apiauthsignupRequest",
        "required": [
          "email",
          "name",
          "password",
          "photo"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "photo": {
            "type": "string"
          }
        },
        "example": {
          "email": "gaxelac@outlook.com",
          "name": "Gaston Axel Lacuesta",
          "password": "123456",
          "photo": ""
        }
      },
      "AddClase-apiclaseaddRequest": {
        "title": "AddClase-apiclaseaddRequest",
        "required": [
          "price",
          "title",
          "description",
          "frecuencia"
        ],
        "type": "object",
        "properties": {
          "price": {
            "type": "integer",
            "format": "int32"
          },
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "frecuencia": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Frecuencium"
            },
            "description": ""
          }
        },
        "example": {
          "price": 5,
          "title": "gaxelac3@outlook.com",
          "description": "blabla",
          "frecuencia": [
            {
              "value": "diaria"
            }
          ]
        }
      },
      "Frecuencium": {
        "title": "Frecuencium",
        "required": [
          "value"
        ],
        "type": "object",
        "properties": {
          "value": {
            "type": "string"
          }
        },
        "example": {
          "value": "diaria"
        }
      }
    },
    "securitySchemes": {
      "httpBearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [
    {
      "httpBearer": []
    }
  ],
  "tags": [
    {
      "name": "Account / Auth"
    },
    {
      "name": "Clases"
    },
    {
      "name": "Profiles"
    }
  ]
}
